# Example config file. Rename it to rase.toml
address = "127.0.0.1"
port = "8000"
thread_count = 100
static_dir = "/srv/rase/static/"
static_url = "/static/"
gzip_min_size = 1024
gzip_max_size = 1048576
gzip_file_types = [
  "js", "txt", "html", "css" 
]
